version: "3.9"
services:

  mongo:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    networks:
      - mongodb

  application:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - mongodb

networks:
  mongodb:
    driver: bridge
